version: "3"
services:
  api:
    image: api
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mongo
    restart: always
    ports:
      - 4000:4000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
